services:
  mysql:
    image: mysql:lts
    container_name: mysql-container
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      #MYSQL_USER: appuser
      #MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: